[10:47:28] [Velocity Async Event Executor - #3/INFO] [com.velocitypowered.proxy.console.VelocityConsole]: lobby-2
[10:47:28] [Velocity Async Event Executor - #3/INFO] [com.velocitypowered.proxy.console.VelocityConsole]: lobby
[10:47:28] [Velocity Async Event Executor - #3/INFO] [com.velocitypowered.proxy.console.VelocityConsole]: false
[10:47:28] [Netty NIO Worker #8/INFO] [com.velocitypowered.proxy.connection.MinecraftConnection]: [server connection] FlaimerPro -> lobby-2 has connected
[10:47:28] [Netty NIO Worker #8/INFO] [com.velocitypowered.proxy.connection.MinecraftConnection]: [server connection] FlaimerPro -> auth has disconnected
[10:47:59] [Velocity Async Event Executor - #5/INFO] [com.velocitypowered.proxy.console.VelocityConsole]: skyblock
[10:47:59] [Velocity Async Event Executor - #5/INFO] [com.velocitypowered.proxy.console.VelocityConsole]: lobby
[10:47:59] [Velocity Async Event Executor - #5/INFO] [com.velocitypowered.proxy.console.VelocityConsole]: false
[10:47:59] [Netty NIO Worker #8/INFO] [com.velocitypowered.proxy.connection.MinecraftConnection]: [server connection] FlaimerPro -> skyblock has connected
[10:47:59] [Netty NIO Worker #8/INFO] [com.velocitypowered.proxy.connection.MinecraftConnection]: [server connection] FlaimerPro -> lobby-2 has disconnected
[10:48:19] [LuckPerms - Task Executor #0/INFO] [luckperms]: [Messaging] Received user update ping for 'flaimerpro' with id: d4926c52-316a-4423-ae83-2a38de035e3c
[10:48:19] [LuckPerms - Task Executor #28/WARN] [me.lucko.luckperms.lib.hikari.pool.PoolBase]: luckperms-hikari - Failed to validate connection me.lucko.luckperms.lib.mariadb.Connection@29f0eb03 ((conn=118) Connection.setNetworkTimeout cannot be called on a closed connection). Possibly consider using a shorter maxLifetime value.
[10:48:19] [LuckPerms - Task Executor #28/WARN] [me.lucko.luckperms.lib.hikari.pool.PoolBase]: luckperms-hikari - Failed to validate connection me.lucko.luckperms.lib.mariadb.Connection@51c9ed2f ((conn=130) Connection.setNetworkTimeout cannot be called on a closed connection). Possibly consider using a shorter maxLifetime value.
[10:48:19] [LuckPerms - Task Executor #28/WARN] [me.lucko.luckperms.lib.hikari.pool.PoolBase]: luckperms-hikari - Failed to validate connection me.lucko.luckperms.lib.mariadb.Connection@7999c683 ((conn=137) Connection.setNetworkTimeout cannot be called on a closed connection). Possibly consider using a shorter maxLifetime value.
[10:48:19] [LuckPerms - Task Executor #28/WARN] [me.lucko.luckperms.lib.hikari.pool.PoolBase]: luckperms-hikari - Failed to validate connection me.lucko.luckperms.lib.mariadb.Connection@571f9240 ((conn=138) Connection.setNetworkTimeout cannot be called on a closed connection). Possibly consider using a shorter maxLifetime value.
[10:48:19] [LuckPerms - Task Executor #28/WARN] [me.lucko.luckperms.lib.hikari.pool.PoolBase]: luckperms-hikari - Failed to validate connection me.lucko.luckperms.lib.mariadb.Connection@54739e8b ((conn=139) Connection.setNetworkTimeout cannot be called on a closed connection). Possibly consider using a shorter maxLifetime value.
[10:48:19] [LuckPerms - Task Executor #28/WARN] [me.lucko.luckperms.lib.hikari.pool.PoolBase]: luckperms-hikari - Failed to validate connection me.lucko.luckperms.lib.mariadb.Connection@4acda1bf ((conn=142) Connection.setNetworkTimeout cannot be called on a closed connection). Possibly consider using a shorter maxLifetime value.
[10:48:19] [LuckPerms - Task Executor #0/INFO] [luckperms]: [Messaging] Received user update ping for 'flaimerpro' with id: 91dd38d2-ede7-4937-84c8-57ce7d26707e
[10:48:19] [LuckPerms - Task Executor #28/WARN] [me.lucko.luckperms.lib.hikari.pool.PoolBase]: luckperms-hikari - Failed to validate connection me.lucko.luckperms.lib.mariadb.Connection@7dd7dbbb ((conn=143) Connection.setNetworkTimeout cannot be called on a closed connection). Possibly consider using a shorter maxLifetime value.
[10:48:19] [LuckPerms - Task Executor #27/WARN] [me.lucko.luckperms.lib.hikari.pool.PoolBase]: luckperms-hikari - Failed to validate connection me.lucko.luckperms.lib.mariadb.Connection@2180c0ba ((conn=148) Connection.setNetworkTimeout cannot be called on a closed connection). Possibly consider using a shorter maxLifetime value.
[10:48:19] [LuckPerms - Task Executor #27/WARN] [me.lucko.luckperms.lib.hikari.pool.PoolBase]: luckperms-hikari - Failed to validate connection me.lucko.luckperms.lib.mariadb.Connection@2f472afa ((conn=156) Connection.setNetworkTimeout cannot be called on a closed connection). Possibly consider using a shorter maxLifetime value.
[10:48:19] [LuckPerms - Task Executor #28/WARN] [me.lucko.luckperms.lib.hikari.pool.PoolBase]: luckperms-hikari - Failed to validate connection me.lucko.luckperms.lib.mariadb.Connection@56f1dbd3 ((conn=150) Connection.setNetworkTimeout cannot be called on a closed connection). Possibly consider using a shorter maxLifetime value.
[10:48:19] [LuckPerms - Task Executor #0/INFO] [luckperms]: [Messaging] Received user update ping for 'flaimerpro' with id: 463738ca-5ee9-4988-8d26-ad6ab475e227
[10:48:22] [LuckPerms - Task Executor #0/INFO] [luckperms]: [Messaging] Received user update ping for 'flaimerpro' with id: dd82520c-a4ca-4096-a10d-9ac1f56054df
[10:48:22] [LuckPerms - Task Executor #0/INFO] [luckperms]: [Messaging] Received user update ping for 'flaimerpro' with id: b79e13e5-d1a2-40d3-b2c7-38ece2f49478
[10:48:22] [LuckPerms - Task Executor #0/INFO] [luckperms]: [Messaging] Received user update ping for 'flaimerpro' with id: 37dad2ef-983f-4a78-bd76-d0ba0d5dc191
[11:02:50] [Netty NIO Worker #8/INFO] [com.velocitypowered.proxy.connection.client.ConnectedPlayer]: [connected player] FlaimerPro (/192.168.1.82:53542): kicked from server skyblock: Server closed
[11:02:50] [Netty NIO Worker #8/INFO] [com.velocitypowered.proxy.connection.MinecraftConnection]: [server connection] FlaimerPro -> skyblock has disconnected
[11:02:50] [Velocity Async Event Executor - #0/INFO] [com.velocitypowered.proxy.console.VelocityConsole]: lobby-2
[11:02:50] [Velocity Async Event Executor - #0/INFO] [com.velocitypowered.proxy.console.VelocityConsole]: lobby
[11:02:50] [Velocity Async Event Executor - #0/INFO] [com.velocitypowered.proxy.console.VelocityConsole]: false
[11:02:50] [Netty NIO Worker #8/INFO] [com.velocitypowered.proxy.connection.MinecraftConnection]: [server connection] FlaimerPro -> lobby-2 has connected
[11:02:58] [Netty NIO Worker #8/INFO] [com.velocitypowered.proxy.connection.client.ConnectedPlayer]: [connected player] FlaimerPro (/192.168.1.82:53542): kicked from server lobby-2: Server closed
[11:02:58] [Netty NIO Worker #8/INFO] [com.velocitypowered.proxy.connection.MinecraftConnection]: [server connection] FlaimerPro -> lobby-2 has disconnected
[11:02:58] [Velocity Async Event Executor - #3/INFO] [com.velocitypowered.proxy.console.VelocityConsole]: auth
[11:02:58] [Velocity Async Event Executor - #3/INFO] [com.velocitypowered.proxy.console.VelocityConsole]: lobby
[11:02:58] [Velocity Async Event Executor - #3/INFO] [com.velocitypowered.proxy.console.VelocityConsole]: false
[11:02:58] [Netty NIO Worker #8/INFO] [com.velocitypowered.proxy.connection.MinecraftConnection]: [server connection] FlaimerPro -> auth has connected
[11:03:02] [Netty NIO Worker #8/INFO] [com.velocitypowered.proxy.connection.client.ConnectedPlayer]: [connected player] FlaimerPro (/192.168.1.82:53542): kicked from server auth: §aСервер перезагружается
[11:03:02] [Netty NIO Worker #8/INFO] [com.velocitypowered.proxy.connection.MinecraftConnection]: [server connection] FlaimerPro -> auth has disconnected
[11:03:02] [Velocity Async Event Executor - #6/INFO] [com.velocitypowered.proxy.console.VelocityConsole]: lobby-2
[11:03:02] [Velocity Async Event Executor - #6/INFO] [com.velocitypowered.proxy.console.VelocityConsole]: lobby
[11:03:02] [Velocity Async Event Executor - #6/INFO] [com.velocitypowered.proxy.console.VelocityConsole]: false
[11:03:02] [Netty NIO Worker #8/ERROR] [com.velocitypowered.proxy.connection.client.ConnectedPlayer]: [connected player] FlaimerPro (/192.168.1.82:53542): unable to connect to server lobby-2
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:21102
Caused by: java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946) ~[?:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337) ~[server.jar:3.3.0-SNAPSHOT (git-44b1e0c6-b412)]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335) ~[server.jar:3.3.0-SNAPSHOT (git-44b1e0c6-b412)]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776) ~[server.jar:3.3.0-SNAPSHOT (git-44b1e0c6-b412)]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[server.jar:3.3.0-SNAPSHOT (git-44b1e0c6-b412)]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[server.jar:3.3.0-SNAPSHOT (git-44b1e0c6-b412)]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[server.jar:3.3.0-SNAPSHOT (git-44b1e0c6-b412)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[server.jar:3.3.0-SNAPSHOT (git-44b1e0c6-b412)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:3.3.0-SNAPSHOT (git-44b1e0c6-b412)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:3.3.0-SNAPSHOT (git-44b1e0c6-b412)]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
[11:03:02] [Netty NIO Worker #8/INFO] [com.velocitypowered.proxy.connection.client.ConnectedPlayer]: [connected player] FlaimerPro (/192.168.1.82:53542) has disconnected: Нет лобби, доступного в качестве запасного варианта.
[11:03:02] [lastloginapi-database-pool/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: [lastloginapi-database-pool] WARN com.alessiodp.lastloginapi.libs.hikari.pool.PoolBase - HikariPool-1 - Failed to validate connection com.alessiodp.lastloginapi.libs.mysql.cj.jdbc.ConnectionImpl@79692adc (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[11:03:02] [lastloginapi-database-pool/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: [lastloginapi-database-pool] WARN com.alessiodp.lastloginapi.libs.hikari.pool.PoolBase - HikariPool-1 - Failed to validate connection com.alessiodp.lastloginapi.libs.mysql.cj.jdbc.ConnectionImpl@324825c6 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[11:03:02] [lastloginapi-database-pool/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: [lastloginapi-database-pool] WARN com.alessiodp.lastloginapi.libs.hikari.pool.PoolBase - HikariPool-1 - Failed to validate connection com.alessiodp.lastloginapi.libs.mysql.cj.jdbc.ConnectionImpl@4e5c165f (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[11:03:02] [lastloginapi-database-pool/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: [lastloginapi-database-pool] WARN com.alessiodp.lastloginapi.libs.hikari.pool.PoolBase - HikariPool-1 - Failed to validate connection com.alessiodp.lastloginapi.libs.mysql.cj.jdbc.ConnectionImpl@7e53fa82 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[11:03:02] [lastloginapi-database-pool/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: [lastloginapi-database-pool] WARN com.alessiodp.lastloginapi.libs.hikari.pool.PoolBase - HikariPool-1 - Failed to validate connection com.alessiodp.lastloginapi.libs.mysql.cj.jdbc.ConnectionImpl@15258eb1 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[11:03:02] [lastloginapi-database-pool/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: [lastloginapi-database-pool] WARN com.alessiodp.lastloginapi.libs.hikari.pool.PoolBase - HikariPool-1 - Failed to validate connection com.alessiodp.lastloginapi.libs.mysql.cj.jdbc.ConnectionImpl@6630efc6 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[11:03:02] [lastloginapi-database-pool/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: [lastloginapi-database-pool] WARN com.alessiodp.lastloginapi.libs.hikari.pool.PoolBase - HikariPool-1 - Failed to validate connection com.alessiodp.lastloginapi.libs.mysql.cj.jdbc.ConnectionImpl@48f0f3b1 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[11:03:02] [lastloginapi-database-pool/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: [lastloginapi-database-pool] WARN com.alessiodp.lastloginapi.libs.hikari.pool.PoolBase - HikariPool-1 - Failed to validate connection com.alessiodp.lastloginapi.libs.mysql.cj.jdbc.ConnectionImpl@291687c7 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[11:03:02] [lastloginapi-database-pool/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: [lastloginapi-database-pool] WARN com.alessiodp.lastloginapi.libs.hikari.pool.PoolBase - HikariPool-1 - Failed to validate connection com.alessiodp.lastloginapi.libs.mysql.cj.jdbc.ConnectionImpl@10ffc452 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[11:03:02] [lastloginapi-database-pool/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: [lastloginapi-database-pool] WARN com.alessiodp.lastloginapi.libs.hikari.pool.PoolBase - HikariPool-1 - Failed to validate connection com.alessiodp.lastloginapi.libs.mysql.cj.jdbc.ConnectionImpl@71d05754 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[11:03:02] [Hikari-Thread #2/WARN] [com.zaxxer.hikari.pool.PoolBase]: GalaxyAPI MySql-HikariPool - Failed to validate connection com.alessiodp.lastloginapi.libs.mysql.cj.jdbc.ConnectionImpl@62b4e752 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[11:03:02] [Hikari-Thread #2/WARN] [com.zaxxer.hikari.pool.PoolBase]: GalaxyAPI MySql-HikariPool - Failed to validate connection com.alessiodp.lastloginapi.libs.mysql.cj.jdbc.ConnectionImpl@6805f3c3 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[11:03:02] [Hikari-Thread #2/WARN] [com.zaxxer.hikari.pool.PoolBase]: GalaxyAPI MySql-HikariPool - Failed to validate connection com.alessiodp.lastloginapi.libs.mysql.cj.jdbc.ConnectionImpl@1ca99302 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[11:03:02] [Hikari-Thread #2/WARN] [com.zaxxer.hikari.pool.PoolBase]: GalaxyAPI MySql-HikariPool - Failed to validate connection com.alessiodp.lastloginapi.libs.mysql.cj.jdbc.ConnectionImpl@10082129 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[11:03:02] [Hikari-Thread #2/WARN] [com.zaxxer.hikari.pool.PoolBase]: GalaxyAPI MySql-HikariPool - Failed to validate connection com.alessiodp.lastloginapi.libs.mysql.cj.jdbc.ConnectionImpl@4d61e000 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[11:03:02] [Hikari-Thread #2/WARN] [com.zaxxer.hikari.pool.PoolBase]: GalaxyAPI MySql-HikariPool - Failed to validate connection com.alessiodp.lastloginapi.libs.mysql.cj.jdbc.ConnectionImpl@abd9984 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[11:03:04] [main/INFO] [com.velocitypowered.proxy.console.VelocityConsole]: §fЭтой команды §cне существует
[11:03:06] [Thread-14/INFO] [com.velocitypowered.proxy.VelocityServer]: Shutting down the proxy...
[11:03:06] [Thread-14/INFO] [com.velocitypowered.proxy.network.ConnectionManager]: Closing endpoint /0.0.0.0:25565
[11:03:06] [Velocity Async Event Executor - #5/INFO] [fallbackservervelocity]: §7[§b!§7] §bFallbackServer §7is disabling... §7[§b!§7]
[11:03:06] [Velocity Async Event Executor - #5/INFO] [lastloginapi]: Disabling LastLoginAPI
[11:03:06] [Velocity Async Event Executor - #5/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: [Velocity Async Event Executor - #5] INFO com.alessiodp.lastloginapi.libs.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
[11:03:06] [Velocity Async Event Executor - #5/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: [Velocity Async Event Executor - #5] INFO com.alessiodp.lastloginapi.libs.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
[11:03:06] [Velocity Async Event Executor - #5/INFO] [lastloginapi]: LastLoginAPI disabled
[11:03:06] [Velocity Async Event Executor - #5/INFO] [simpleautomessages]: Disabling SimpleAutoMessages
[11:03:06] [Velocity Async Event Executor - #5/INFO] [simpleautomessages]: SimpleAutoMessages disabled
[11:03:06] [Velocity Async Event Executor - #5/INFO] [com.zaxxer.hikari.HikariDataSource]: GalaxyAPI MySql-HikariPool - Shutdown initiated...
[11:03:06] [Velocity Async Event Executor - #5/INFO] [com.zaxxer.hikari.HikariDataSource]: GalaxyAPI MySql-HikariPool - Shutdown completed.
[11:03:06] [Velocity Async Event Executor - #5/INFO] [luckperms]: Starting shutdown process...
[11:03:06] [Velocity Async Event Executor - #5/INFO] [luckperms]: Closing messaging service...
[11:03:06] [Velocity Async Event Executor - #5/INFO] [luckperms]: Closing storage...
[11:03:06] [Velocity Async Event Executor - #5/INFO] [me.lucko.luckperms.lib.hikari.HikariDataSource]: luckperms-hikari - Shutdown initiated...
[11:03:06] [Velocity Async Event Executor - #5/INFO] [me.lucko.luckperms.lib.hikari.HikariDataSource]: luckperms-hikari - Shutdown completed.
[11:03:06] [Velocity Async Event Executor - #5/INFO] [luckperms]: Goodbye!
